use_frameworks!

platform :ios, '15.0'

target 'AIChatBotiOSSDK_Example' do
  pod 'AIChatBotiOSSDK', :path => '../'
  
  pod 'Starscream' , '~> 4.0.8'
  pod 'IQKeyboardManagerSwift'

  target 'AIChatBotiOSSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
