use_frameworks!

platform :ios, '10.0'

target 'AIChatBotiOSSDK_Example' do
  pod 'AIChatBotiOSSDK', :path => '../'

  target 'AIChatBotiOSSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
